In [1]:
# Libraries
import pandas as pd

In [2]:
# Max rows and columns - any of the options below works

# print(pd.get_option('display.max_columns'), pd.get_option('display.max_rows'))
print("Defaults: max_col: {}, max_rows: {}, col_width:{}, Number of decimal places: {}".\
      format(pd.get_option('max_columns'), 
             pd.get_option('max_rows'),
             pd.get_option('max_colwidth'),
             pd.get_option('precision')
            )
)

Defaults: max_col: 20, max_rows: 60, col_width:50, Number of decimal places: 6

In [3]:
# remove limits on number of rows and columns to display - any of the options below works

# pd.set_option('display.max_columns',None)
# pd.set_option('display.max_rows',None)

pd.set_option('max_columns',None)
pd.set_option('max_rows',None)
# pd.set_option('max_colwidth',None)

In [18]:
extras = pd.read_excel('s3://alpha-omppg/Recalls/PPUD/Extra Variables/PPUD_Recalls_2022Q3_Extra.xls')
recalls = pd.read_excel('s3://alpha-omppg/Recalls/PPUD/Audited/PPUD_Recalls_2022Q3.xls')

In [4]:
extras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6210 entries, 0 to 6209
Data columns (total 41 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   ALT_FILE_REFERENCE                          396 non-null    object
 1   CRO_PNC                                     6207 non-null   object
 2   CUSTODY_TYPE_DESCRIPTION                    6210 non-null   object
 3   CUSTODY_TYPE_AT_TIME_OF_RECALL_DESCRIPTION  6210 non-null   object
 4   DOB                                         6210 non-null   object
 5   DOS                                         6210 non-null   object
 6   DETERMINATE_FLAG                            6210 non-null   bool
 7   ETHNICITY_DESCRIPTION                       6210 non-null   object
 8   EWS_NUMBER                                  5124 non-null   object
 9   FAMILY_NAME                                 6210 non-null   object
 10  FILE_REFERENCE                              6210 non-null   object
 11  FIRST_NAMES                                 6210 non-null   object
 12  GENDER                                      6210 non-null   object
 13  INDEX_OFFENCE_DESCRIPTION                   6210 non-null   object
 14  ISSUE_REVOCATION_TARGET                     6210 non-null   object
 15  LICENCE_END                                 6210 non-null   object
 16  LICENCE_REVOKE_DATE                         6210 non-null   object
 17  LICENCE_START                               6210 non-null   object
 18  TYPE_OF_LICENCE_DESCRIPTION                 6210 non-null   object
 19  MAPPA_LEVEL_DESCRIPTION                     6210 non-null   object
 20  NATIONALITY_DESCRIPTION                     6210 non-null   object
 21  NOMS_ID                                     6210 non-null   object
 22  NOMS_REGION_DESCRIPTION                     6210 non-null   object
 23  NUMBER_OF_RECALL_REASONS                    6210 non-null   int64
 24  OFFENDER_OWNING_TEAM_DESCRIPTION            6210 non-null   object
 25  STATUS_DESCRIPTION                          6210 non-null   object
 26  PB_DECISION_AFTER_BREACH_ACTUAL             6210 non-null   object
 27  POLICE_FORCE_DESCRIPTION                    6210 non-null   object
 28  PRISON_NUMBER                               6210 non-null   object
 29  PROBATION_AREA_DESCRIPTION                  6210 non-null   object
 30  RECALL_REASON_DESCRIPTIONS                  6210 non-null   object
 31  RECALL_TYPE_DESCRIPTION                     6210 non-null   object
 32  RECOMMEND_TO_EO_CWORKER_NAME                6210 non-null   object
 33  REPORT_RECD_BY_UNIT_ACTUAL                  6210 non-null   object
 34  REPORT_RECD_BY_UNIT_TARGET                  6210 non-null   object
 35  RESCIND_FLAG                                6210 non-null   bool
 36  REVOCATION_ISSUED_BY_NAME                   6210 non-null   object
 37  RTC_DATE                                    6210 non-null   object
 38  RTC_TARGET                                  6210 non-null   object
 39  TARIFF_EXPIRY_DATE                          6210 non-null   object
 40  UAL_FLAG                                    6210 non-null   bool
dtypes: bool(3), int64(1), object(37)
memory usage: 1.8+ MB

In [16]:
extras.head()

,ALT_FILE_REFERENCE,CRO_PNC,CUSTODY_TYPE_DESCRIPTION,CUSTODY_TYPE_AT_TIME_OF_RECALL_DESCRIPTION,DOB,DOS,DETERMINATE_FLAG,ETHNICITY_DESCRIPTION,EWS_NUMBER,FAMILY_NAME,FILE_REFERENCE,FIRST_NAMES,GENDER,INDEX_OFFENCE_DESCRIPTION,ISSUE_REVOCATION_TARGET,LICENCE_END,LICENCE_REVOKE_DATE,LICENCE_START,TYPE_OF_LICENCE_DESCRIPTION,MAPPA_LEVEL_DESCRIPTION,NATIONALITY_DESCRIPTION,NOMS_ID,NOMS_REGION_DESCRIPTION,NUMBER_OF_RECALL_REASONS,OFFENDER_OWNING_TEAM_DESCRIPTION,STATUS_DESCRIPTION,PB_DECISION_AFTER_BREACH_ACTUAL,POLICE_FORCE_DESCRIPTION,PRISON_NUMBER,PROBATION_AREA_DESCRIPTION,RECALL_REASON_DESCRIPTIONS,RECALL_TYPE_DESCRIPTION,RECOMMEND_TO_EO_CWORKER_NAME,REPORT_RECD_BY_UNIT_ACTUAL,REPORT_RECD_BY_UNIT_TARGET,RESCIND_FLAG,REVOCATION_ISSUED_BY_NAME,RTC_DATE,RTC_TARGET,TARIFF_EXPIRY_DATE,UAL_FLAG
0,NaN,80641/22W,Determinate,Determinate,29/04/1998 00:00:00,02/02/2022 00:00:00,True,White - Other,02RC/1426528E15072,Lleshi,PPU_394263,Altin,M,POSSESSION DRUG,16/07/2022 16:02:00,10/11/2022 00:00:00,15/07/2022 17:44:00,10/06/2022 00:00:00,Standard,Not Applicable,Not Specified,A3946ET,PS-Yorkshire and The Humber,2,Recall Team,Recalled [*],15/07/2022 10:00:00,South Yorkshire Police,26528E,PS - Sheffield,"Poor Behaviour - non-compliance, Failed to kee...",14 Day Fixed Term Recall - Under 12 Months,Afua Frimpong,15/07/2022 16:02:00,16/07/2022 10:00:00,False,oooBrenda Campos,00/01/1900 00:00:00,19/07/2022 17:44:00,00/01/1900 00:00:00,True
1,NaN,87718/21G,Determinate,Determinate,08/01/1981 00:00:00,13/01/2022 00:00:00,True,Chinese,02RC/0712264E16092,Cheng,PPU_397348,Wei,M,THREATENING / DISORDERLY BEHAVIOUR,17/09/2022 14:59:00,12/01/2023 00:00:00,16/09/2022 16:17:00,22/04/2022 00:00:00,Standard,Level 2 - Multi-Agency Management,Not Specified,A7995ER,PS-North West,2,Recall Team,Recalled [*],15/09/2022 16:00:00,Cheshire Constabulary,12264E,PS - Crewe,"Failed to reside, Poor Behaviour - non-compliance",Standard Recall - Over 12 Months,Afua Frimpong,16/09/2022 14:59:00,16/09/2022 16:00:00,False,Simon O'Rourke,00/01/1900 00:00:00,20/09/2022 16:17:00,00/01/1900 00:00:00,True
2,NaN,98777/22J,Determinate,Determinate,20/09/1972 00:00:00,27/06/2022 00:00:00,True,White - Other,02RC/4458629E19082,Ciubotariu,PPU_396468,Dumitru,M,DRIVING UNDER THE INFLUENCE OF DRINK/DRUGS,20/08/2022 12:29:00,18/09/2022 00:00:00,19/08/2022 16:52:00,05/08/2022 00:00:00,Standard,Not Applicable,Not Specified,A7841EV,PS-South Central,2,Recall Team,Recalled [*],19/08/2022 12:10:00,Hampshire Constabulary,58629E,PS - Hampshire North and East,"Failed to reside, Poor Behaviour - non-compliance",14 Day Fixed Term Recall - Under 12 Months,Louise Adeoba,19/08/2022 12:29:00,20/08/2022 12:10:00,False,Claire Owens,00/01/1900 00:00:00,23/08/2022 16:52:00,00/01/1900 00:00:00,True
3,NaN,NaN,Determinate,Determinate,07/10/1996 00:00:00,04/06/2022 00:00:00,True,White - Other,02RC/1054208E31082,Yankov,PPU_396772,Krasmir Asenov,M,FRAUD,31/08/2022 14:45:00,18/11/2022 00:00:00,31/08/2022 10:02:00,26/08/2022 00:00:00,Standard,Not Applicable,BULGARIA ( BG ),A5983EV,PS-North East,1,Recall Team,Recalled [*],30/08/2022 12:30:00,Northumbria Police,54208E,PS - Newcastle Upon Tyne,Failed to keep in touch,14 Day Fixed Term Recall - Under 12 Months,Estelle Donnan,30/08/2022 14:45:00,31/08/2022 12:30:00,False,Simon Dickie,00/01/1900 00:00:00,04/09/2022 10:02:00,00/01/1900 00:00:00,True
4,NaN,NaN,Determinate,Determinate,04/11/1999 00:00:00,19/07/2021 00:00:00,True,White - Other,02RC/0185231D27072,Toskaj,PPU_394653,Ardian,M,PRODUCTION DRUG,28/07/2022 12:59:00,02/06/2023 00:00:00,27/07/2022 15:16:00,14/07/2022 00:00:00,Standard,Not Applicable,Not Specified,A6536EQ,PS-London,2,Recall Team,Recalled [*],26/07/2022 16:00:00,Met Police Service,85231D,PS - Harrow,"Failed to reside, Failed to keep in touch",28 Day Fixed Term Recall - Over 12 Months,Samantha Wasley,27/07/2022 12:59:00,27/07/2022 16:00:00,False,Simon Dickie,00/01/1900 00:00:00,31/07/2022 15:16:00,00/01/1900 00:00:00,True

In [19]:
recalls.head()

,ALT_FILE_REFERENCE,CRO_PNC,CUSTODY_TYPE_DESCRIPTION,CUSTODY_TYPE_AT_TIME_OF_RECALL_DESCRIPTION,DOB,DETERMINATE_FLAG,ETHNICITY_DESCRIPTION,EWS_NUMBER,FAMILY_NAME,FILE_REFERENCE,FIRST_NAMES,GENDER,INDEX_OFFENCE_DESCRIPTION,ISSUE_REVOCATION_TARGET,LICENCE_REVOKE_DATE,TYPE_OF_LICENCE_DESCRIPTION,MAPPA_LEVEL_DESCRIPTION,NATIONALITY_DESCRIPTION,NOMS_ID,NOMS_REGION_DESCRIPTION,STATUS_DESCRIPTION,PB_DECISION_AFTER_BREACH_ACTUAL,POLICE_FORCE_DESCRIPTION,PRISON_NUMBER,PROBATION_AREA_DESCRIPTION,RECALL_TYPE_DESCRIPTION,REPORT_RECD_BY_UNIT_ACTUAL,REPORT_RECD_BY_UNIT_TARGET,RESCIND_FLAG,RTC_DATE,RTC_TARGET,UAL_FLAG,OFFENDER_OWNING_TEAM_DESCRIPTION,RTC_NOTIF_METHOD_DESCRIPTION
0,NaN,48908/93R,Determinate,Determinate,10/07/1980 00:00:00,True,White - British,02RC/2089797B01072,Ward,PPU_191485,Charles Christopher,M,BURGLARY,01/07/2022 15:03:00,01/07/2022 08:40:00,Standard,Not Applicable,UNITED KINGDOM ( UK ),A5940AG,PS-West Midlands,Recalled [*],30/06/2022 10:00:00,West Midlands Police,89797B,PS - Wolverhampton,Standard Recall - Over 12 Months,30/06/2022 15:03:00,01/07/2022 10:00:00,False,13/08/2022 13:58:00,05/07/2022 08:40:00,False,Recall Team,UAL Check
1,NaN,133027/88T,Determinate,Determinate,09/04/1974 00:00:00,True,White - British,02RC/1186432D01072,Mark,PPU_393700,Andrew Phillip,M,POSSESSION DRUGS WITH INTENT TO SUPPLY,01/07/2022 15:10:00,01/07/2022 08:55:00,Standard,Not Applicable,UNITED KINGDOM ( UK ),A9662AR,PS-North East,Recalled [*],30/06/2022 09:15:00,Durham Constabulary,65947D,PS - Durham,28 Day Fixed Term Recall - Over 12 Months,30/06/2022 15:10:00,01/07/2022 09:15:00,False,20/07/2022 18:15:00,05/07/2022 08:55:00,False,Recall Team,UAL Check
2,NaN,145792/21F,Determinate,Determinate,25/05/1986 00:00:00,True,White - British,02RC/6228483E01072,Jones,PPU_393701,Kyle,M,BREACH OF RESTRAINING ORDER,01/07/2022 15:34:00,01/07/2022 09:00:00,Standard,Not Applicable,UNITED KINGDOM ( UK ),A4859ET,PS-Wales,Recalled [*],30/06/2022 12:22:00,South Wales Police / Heddlu De Cymru,2747938 / 28483E,PS - Cardiff and Vale,Standard Recall - Over 12 Months,30/06/2022 15:34:00,01/07/2022 12:22:00,False,04/07/2022 16:40:00,05/07/2022 09:00:00,False,Recall Team,UAL Check
3,NaN,105699/93W,Determinate,Determinate,17/08/1975 00:00:00,True,White - British,02RC/0752359E01072,Hobbs,PPU_207538,Lee,M,POSSESSION OF AN OFFENSIVE WEAPON,01/07/2022 15:55:00,01/07/2022 09:20:00,Standard,Not Applicable,UNITED KINGDOM ( UK ),A3341DM,PS-North West,Recalled [*],30/06/2022 11:00:00,Cheshire Constabulary,52359E,PS - Crewe,14 Day Fixed Term Recall - Under 12 Months,30/06/2022 15:55:00,01/07/2022 11:00:00,False,04/07/2022 15:56:00,05/07/2022 09:20:00,False,Recall Team,UAL Check
4,NaN,76927/92Q,Determinate,Determinate,14/03/1975 00:00:00,True,White - British,02RC/20K5114801072,Hatton,PPU_178020,Jason,M,Burglary (stealing - in dwelling),01/07/2022 15:40:00,01/07/2022 09:35:00,Standard,Level 1 - Multi-Agency Support,UNITED KINGDOM ( UK ),A7488AX,PS-West Midlands,Recalled [*],30/06/2022 12:00:00,West Midlands Police,K51148,PS - Birmingham North and East,Standard Recall - Over 12 Months,30/06/2022 15:40:00,01/07/2022 12:00:00,False,04/08/2022 18:49:00,05/07/2022 09:35:00,False,Recall Team,UAL Check

In [29]:
recalls = recalls[recalls["LICENCE_REVOKE_DATE"].notna() & recalls["FAMILY_NAME"].notna()]
lyll''lll

In [21]:
"licence_revoke_date".upper()

'LICENCE_REVOKE_DATE'

In [27]:
recalls["LICENCE_REVOKE_DATE"].notna() and recalls["FAMILY_NAME"].notna()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# if required reset defaults on number of rows and columns to display - any of the options below works

# pd.reset_option('max_columns')
# pd.reset_option('max_rows')